project_id: 502106                                   #open project and go to Tools > API 
api_token: 8300f76ee36bb6c4dfb762df99e9186b          #open profile settings and go to API > New Token > create Token
base_path: .
base_url: https://api.crowdin.com/
preserve_hierarchy": true

files: [
  {
    source: /doc/en/**/*.po
    translation: /doc/%two_letters_code%/**/%original_file_name%
  }
]
